from django.conf.urls import include, url
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
from django.contrib.auth import views as auth_views
from wowardrobe import views

urlpatterns = [
    url(r'^home$', views.home, name='home'),
    url(r'^create$',views.create, name = 'create'),
    url(r'^upload_clothes$', views.upload_clothes, name='upload'),
    url(r'^mywardrobe$',views.mywardrobe, name = 'mywardrobe'),
    url(r'^view_clothes', views.view_clothes_by_tag, name='viewClothesByTag'),
    url(r'^view_outfits', views.view_outfits_by_tag, name='viewOutfitsByTag'),
    url(r'^search', views.search_by_tags, name='searchByTags'),
    url(r'^clothes_search', views.search_by_tags_outfit,name='searchByTagsOutfit'),
    url('^outfits_search', views.search_outfits_by_tags, name='searchOutfitsByTags'),
    url(r'^get_tags$',views.get_tags, name = 'getTagList'),
    url(r'remove_clothes/(?P<id>\d+)$',views.remove_clothes, name='remove_clothes'),
    url(r'^get_image/(?P<id>\d+)$', views.get_image, name='get_image'),
    url(r'^get_image_by_tag/(?P<tag>\d+)$', views.get_image_by_tag, name='get_image_by_tag'),
    url(r'^edit_clothes/(?P<id>\d+)$',views.edit_clothes, name ='edit_clothes'),
    url(r'^signin', views.signin, name = 'signin'),
    url(r'^login$', login, {'template_name':'wowardrobe/signin.html'}, name='login'),
    url(r'^logout$', logout_then_login, name='logout'),
    url(r'^register$', views.register, name='register'),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$',views.confirm_registration, name='confirm'),
    url(r'^create_outfit$',views.create_outfit,name = 'create_outfit'),
    url(r'^mylookbook$', views.mylookbook, name = 'mylookbook'),
    url(r'^dailyoutfit$', views.daily_outfit, name = 'dailyoutfit'),
    url(r'^upload_outfit$', views.upload_outfit, name='upload_outfit'),
    url(r'^overview$', views.get_overview, name='overview'),
    url(r'^get_category_count$', views.get_category_count, name='get_category_count'),
    url(r'^get_top_count$', views.get_tops_count, name='get_top_count'),
    url(r'^get_bottom_count$', views.get_bottoms_count, name='get_bottom_count'),
    url(r'^get_shoes_count$', views.get_shoes_count, name='get_shoes_count'),
    url(r'^get_color_count$', views.get_color_count, name='get_color_count'),
    url(r'get_style_count$', views.get_style_count, name='get_style_count'),
    url(r'get_brand_count$', views.get_brand_count, name='get_brand_count'),
    url(r'get_season_count$', views.get_season_count, name='get_season_count'),
    url(r'get_event_count$', views.get_event_count, name='get_event_count'),
    url(r'get_event_tags$', views.get_event_tags, name='get_event_tags'),
    url(r'get_style_tags$', views.get_style_tags, name='get_style_tags'),
    url(r'get_recommendation_by_params', views.get_recommendation_by_params, name='get_recommendation_by_params'),
    url(r'get_recommendation', views.get_recommendation, name='get_recommendation'),
    url(r'^edit_profile$',views.edit_profile,name = 'edit_profile'),
    url(r'^get_profile_image/(?P<user_id>\d+)$',views.get_profile_image,name = 'get_profile_image'),
    url(r'^expand$', views.expand_wardrobe, name='expand_wardrobe'),
    url(r'^get_clothes_by_budget', views.get_clothes_by_budget, name='get_clothes_by_budget'),
    url(r'^save_outfit_to_schedule', views.save_outfit_to_schedule, name='save_outfit_to_schedule'),
    url(r'^view_schedule', views.view_schedule, name='view_schedule'),
    url(r'^edit_outfit/(?P<id>\d+)$',views.edit_outfit,name = 'edit_outfit'),
    url(r'^remove_outfit/(?P<id>\d+)$',views.remove_outfit,name = 'remove_outfit'),
    url(r'^view_profile$',views.view_profile,name = 'view_profile'),
]
