# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to='clothes_image')),
                ('category', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('style', models.CharField(blank=True, max_length=255)),
                ('event', models.CharField(blank=True, max_length=255)),
                ('season', models.CharField(blank=True, max_length=255)),
                ('weather', models.CharField(blank=True, max_length=255)),
                ('temperature_level', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyOutfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Outfits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('counts', models.IntegerField(blank=True, default=0)),
                ('last_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('isFavorite', models.BooleanField(default=False)),
                ('temperature_level', models.IntegerField(blank=True, default=-1)),
                ('tags', models.TextField(default='')),
                ('bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom', to='wowardrobe.Clothes')),
                ('dress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dress', to='wowardrobe.Clothes')),
                ('shoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='wowardrobe.Clothes')),
                ('top1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top1', to='wowardrobe.Clothes')),
                ('top2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top2', to='wowardrobe.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=10)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowardrobe.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile_image/profile_placeholder.png', upload_to='profile_image')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email_confirm', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailyoutfit',
            name='today',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today', to='wowardrobe.Outfits'),
        ),
        migrations.AddField(
            model_name='dailyoutfit',
            name='tomorrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tomorrow', to='wowardrobe.Outfits'),
        ),
        migrations.AddField(
            model_name='dailyoutfit',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
