# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowardrobe', '0002_auto_20171202_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfits',
            name='isFavorite',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='tags',
        ),
        migrations.AddField(
            model_name='outfits',
            name='event',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outfits',
            name='season',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outfits',
            name='style',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='outfits',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
